IF DB_ID('DeviceManagement') IS NULL
	CREATE DATABASE DeviceManagement;
GO

USE DeviceManagement;
GO
IF OBJECT_ID('Users', 'U') IS NULL
	CREATE TABLE Users (
		UserID INT PRIMARY KEY IDENTITY,
		Name NVARCHAR(100) NOT NULL,
		Email NVARCHAR(50) NOT NULL,
		PasswordHash NVARCHAR(255) NOT NULL,
		Role NVARCHAR(50) NULL,
		Location NVARCHAR(100) NULL);

IF OBJECT_ID('Devices', 'U') IS NULL
	CREATE TABLE Devices (
		DeviceID INT PRIMARY KEY IDENTITY,
		Name NVARCHAR(100) NOT NULL,
		Manufacturer NVARCHAR(100) NOT NULL,
		Type NVARCHAR(50) NOT NULL,
		OperatingSystem NVARCHAR(50) NOT NULL,
		OSVersion NVARCHAR(50) NOT NULL,
		Processor NVARCHAR(100) NOT NULL,
		RAMAmount INT NOT NULL,
		Description NVARCHAR(200) NULL);

IF OBJECT_ID('DeviceAssignments', 'U') IS NULL
	CREATE TABLE DeviceAssignments (
		DeviceAssignmentID INT PRIMARY KEY IDENTITY,
		UserID INT FOREIGN KEY REFERENCES Users(UserID) NOT NULL,
		DeviceID INT FOREIGN KEY REFERENCES Devices(DeviceID) NOT NULL,
		AssignedAt DATETIME NOT NULL DEFAULT GETDATE(),
		UnassignedAt DATETIME NULL);
		